name: Deploy Next.js App

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Assuming this runner is set up on your Nginx server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Make sure this version matches your server's Node.js installation

    - name: Install Dependencies
      run: npm install

    - name: Inject version
      run: |
        echo "NEXT_PUBLIC_APP_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
        echo "TEST=${{ secrets.TEST }}" >> $GITHUB_ENV
        echo "Test bob: ${{ secrets.TEST }}"

    - name: Log Test Environment Variable
      run: echo "Value of TEST is $TEST"


    - name: Build
      run: npm run build
  
    - name: Stop old PM2 application
      run: pm2 delete ecosystem.config.js

    - name: Reload application with PM2
      run: pm2 reload ecosystem.config.js


